mx nice

diff --git a/bin/mx b/bin/mx
--- a/bin/mx
+++ b/bin/mx
@@ -1,10 +1,20 @@
 #!/bin/bash
 
+# set -e pipefail
+
 # Ensure first argument is provided
 if [ -z "$1" ]; then
   echo "Usage: $0 <session-name>"
   exit 1
 fi
 
-fzf "$1"
+# Find a dir
+dir="$(zoxide query "$1")"
+if [ $? -ne 0 ]; then
+    echo "could not find a match for $1"
+    exit 1
+fi
+
+# Change the dir
+cd "$dir" || exit 1
 zellij --layout main
